# Generated by Django 4.2.2 on 2024-04-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='default_password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(default='default', max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='default_password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
