# Generated by Django 4.2.2 on 2024-04-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
