# Generated by Django 4.2.2 on 2024-04-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
